const kb = require('./kb.js');
const { nameLine, bigTitle, subtitle, meta, rule, header, body, subhead, lead, numbered, bullet, ouinon, quote, signature, golden, build, NAVY, RED } = kb;

// ============ 1. CULTURE ============
async function culture() {
  const k = [];
  k.push(nameLine("K E B R A N E"));
  k.push(bigTitle("Le Livre", { before: 120, after: 0 }));
  k.push(bigTitle("de la Culture", { after: 60 }));
  k.push(subtitle("Comment nous travaillons, comment nous décidons, comment nous recrutons."));
  k.push(meta("Document fondateur   ·   Version 1.0"));
  k.push(rule());
  k.push(header("COMMENT LIRE CE LIVRE"));
  k.push(body("La culture n'est pas ce qui est écrit sur un mur. C'est la somme des comportements que nous récompensons et de ceux que nous refusons."));
  k.push(body("Ce livre ne décrit pas l'entreprise que nous aimerions être. Il décrit comment nous décidons, travaillons et recrutons quand personne ne regarde. Le jour où un texte de ce livre contredit nos actes, il faut corriger l'un ou l'autre, jamais faire semblant."));
  k.push(body("Il prolonge Le Manifeste de Kebrane. Le manifeste dit pourquoi nous existons. Celui-ci dit comment nous nous comportons."));
  k.push(header("CE QUE NOUS SOMMES"));
  k.push(body("Une petite équipe, répartie sur plusieurs pays et plusieurs langues, qui construit des outils durables pour des gens que le monde a rendus invisibles."));
  k.push(body("Nous travaillons entre le Cameroun, l'Allemagne et ailleurs, en français, en allemand et en anglais. Notre petite taille n'est pas une faiblesse à cacher, c'est une discipline : chaque personne compte, chaque décision se voit, personne ne se cache derrière un organigramme."));
  k.push(header("COMMENT NOUS TRAVAILLONS"));
  k.push(lead("Écrire d'abord.", "Répartis sur plusieurs fuseaux et plusieurs langues, nous ne comptons pas sur le hasard des couloirs. Ce qui n'est pas écrit n'existe pas. On écrit les décisions, pas seulement les conversations. Un document clair vaut mieux qu'une réunion brillante."));
  k.push(lead("Asynchrone par défaut.", "La réunion est un coût, pas une preuve de travail. On se réunit quand l'écrit ne suffit plus, jamais par réflexe. Le temps de concentration est un bien rare, on le protège."));
  k.push(lead("Profondeur, pas présence.", "Nous ne mesurons pas les heures assises. De même que nous refusons de juger notre succès au temps que nos utilisateurs passent sur nos plateformes, nous refusons de juger le nôtre au temps passé à notre bureau. Ce qui compte, c'est la barrière supprimée."));
  k.push(lead("Autonomie et responsabilité.", "Chacun est propriétaire de son domaine. La liberté d'agir vient avec le devoir de rendre des comptes. On ne demande pas la permission, on informe et on assume."));
  k.push(lead("Livrer, puis améliorer.", "La clarté avant la vitesse, mais la vitesse quand même. Un produit imparfait entre les mains d'un utilisateur vaut mieux qu'un produit parfait resté dans nos têtes."));
  k.push(header("COMMENT NOUS COMMUNIQUONS"));
  k.push(lead("Direct et bienveillant.", "On dit la vérité tôt, même quand elle dérange. La franchise sans respect est de la brutalité ; le respect sans franchise est de la lâcheté. On vise les deux à la fois."));
  k.push(lead("Le désaccord est un cadeau.", "Celui qui n'est pas d'accord et se tait vole une décision à l'équipe. On exprime son désaccord, on argumente, puis on s'engage derrière la décision prise, même quand ce n'était pas la sienne."));
  k.push(lead("La langue n'est jamais une barrière, chez nous non plus.", "Français, allemand, anglais : on s'adapte pour être compris, pas pour paraître. Personne n'est jugé sur son accent ou ses fautes, seulement sur ses idées. Ce serait absurde de combattre les barrières dehors et d'en dresser à l'intérieur."));
  k.push(lead("Pas de politique.", "L'énergie dépensée à gérer les ego est de l'énergie volée aux utilisateurs."));
  k.push(header("COMMENT NOUS DÉCIDONS"));
  k.push(lead("Toute décision commence par une question.", "Quelle barrière supprime-t-on, et pour qui ? Si la réponse n'est pas claire, la décision attend."));
  k.push(lead("Portes à sens unique, portes à double sens.", "Une décision réversible se prend vite, et souvent seul. Une décision irréversible se prend lentement, et à plusieurs. Ne jamais confondre les deux : la lenteur sur le réversible tue l'élan, la vitesse sur l'irréversible tue l'entreprise."));
  k.push(lead("Une décision a toujours un responsable.", "Pas de décision orpheline. Une personne nommée tranche, écrit la décision et son pourquoi. On a le droit d'être en désaccord avec elle, pas avec le fait qu'elle existe."));
  k.push(lead("En cas de doute, le manifeste tranche.", "L'option qui rend l'utilisateur plus autonome, même si elle nous rapporte moins. C'est écrit, c'est la règle, on ne la renégocie pas à chaque réunion."));
  k.push(header("COMMENT NOUS RECRUTONS"));
  k.push(lead("Le caractère avant le CV.", "Un diplôme prouve un passé, pas un avenir. On recrute des gens curieux, autonomes, obsédés par le problème et non par la technologie. Les compétences s'apprennent, le caractère beaucoup moins."));
  k.push(lead("Le seuil.", "On ne recrute pas quelqu'un qui fera l'affaire. On recrute quelqu'un qui rend l'équipe meilleure qu'avant son arrivée. Dans le doute, c'est non."));
  k.push(lead("La diversité est un avantage, pas une case à cocher.", "Nous servons des gens de langues, de pays et de parcours différents. Une équipe qui leur ressemble comprend leurs barrières mieux que n'importe quelle étude de marché."));
  k.push(lead("Les questions que nous posons.", "Raconte une barrière que tu as supprimée pour quelqu'un. Raconte une fois où tu t'es trompé, et ce que tu en as fait. Qu'as-tu appris seul, sans que personne te le demande ?"));
  k.push(lead("Recruter lentement, se séparer avec respect.", "On prend le temps de bien choisir. Et quand une séparation devient nécessaire, elle se fait tôt, avec honnêteté et dignité. Personne ne devrait apprendre en partant ce qu'il aurait dû entendre en restant."));
  k.push(header("CE QUE NOUS NE TOLÉRONS PAS"));
  k.push(body("Une culture se définit autant par ce qu'elle refuse que par ce qu'elle célèbre."));
  k.push(bullet("L'esbroufe : ", "impressionner au lieu de résoudre."));
  k.push(bullet("La dépendance créée exprès : ", "retenir l'utilisateur au lieu de le rendre autonome."));
  k.push(bullet("Le culte des heures : ", "confondre l'agitation avec le travail."));
  k.push(bullet("Le mépris : ", "envers un collègue, un utilisateur ou un candidat."));
  k.push(bullet("La politique interne : ", "servir son ego avant la mission."));
  k.push(bullet("Le silence complice : ", "voir un problème et ne rien dire."));
  k.push(header("LE RITUEL DE LA SEMAINE"));
  k.push(body("Quelle barrière avons-nous supprimée cette semaine ?"));
  k.push(body("Chaque semaine, chacun répond à cette question par écrit, en une phrase. Ce n'est pas un rapport d'activité, c'est une preuve d'impact. Une semaine sans réponse arrive, et ce n'est pas grave. Mais si la réponse reste vide trop souvent, ce n'est pas la personne qui a un problème, c'est ce sur quoi nous l'avons laissée travailler."));
  k.push(header("LA CULTURE N'EST PAS FIGÉE"));
  k.push(body("Ce livre est une version, pas une vérité éternelle. La culture se vit, se corrige et se transmet. Chaque nouvelle recrue en hérite, et a le droit de la questionner. Le jour où plus personne ne la questionne, elle est déjà morte."));
  k.push(golden("La règle d'or : on ne juge pas les gens sur ce qu'ils disent croire, mais sur ce qu'ils font quand c'est difficile."));
  await build("Le-Livre-de-la-Culture-Kebrane.docx", "Le Livre de la Culture Kebrane", k);
}

// ============ 2. IDENTITÉ VERBALE ============
async function identite() {
  const k = [];
  k.push(nameLine("K E B R A N E"));
  k.push(bigTitle("L'Identité", { before: 120, after: 0 }));
  k.push(bigTitle("verbale", { after: 60 }));
  k.push(subtitle("Comment Kebrane parle : voix, ton, mots, nommage. L'identité visuelle viendra ensuite."));
  k.push(meta("Document fondateur   ·   Version 0.9"));
  k.push(rule());
  k.push(header("AVANT LE LOGO, LA VOIX"));
  k.push(body("Une marque n'a pas seulement une allure, elle a une voix. Ce livre fixe comment Kebrane parle, avant même de savoir à quoi elle ressemble. Le logo, les couleurs et la typographie viendront ensuite, et devront s'accorder à cette voix, pas l'inverse."));
  k.push(body("On doit reconnaître Kebrane à la façon dont elle s'adresse à toi, les yeux fermés."));
  k.push(header("NOTRE VOIX NE CHANGE JAMAIS"));
  k.push(body("La voix, c'est qui nous sommes quand nous parlons : elle est constante. Le ton, lui, s'adapte. Quatre traits définissent la voix de Kebrane."));
  k.push(subhead("Claire avant d'être élégante."));
  k.push(ouinon("Oui :", "des phrases courtes, un mot simple, une idée à la fois.", NAVY));
  k.push(ouinon("Non :", "de la belle langue qui oblige à relire pour comprendre.", RED));
  k.push(subhead("Chaleureuse, jamais paternaliste."));
  k.push(ouinon("Oui :", "on s'adresse à un adulte capable, que l'on accompagne.", NAVY));
  k.push(ouinon("Non :", "on ne materne pas, on ne félicite pas pour un rien, on ne prend personne de haut.", RED));
  k.push(subhead("Honnête, même quand c'est moins vendeur."));
  k.push(ouinon("Oui :", "on nomme ce qui est difficile ; on promet un meilleur chemin, pas le succès.", NAVY));
  k.push(ouinon("Non :", "pas de « garanti », pas de « 100 % », pas de fausse facilité.", RED));
  k.push(subhead("Sobre, jamais tapageuse."));
  k.push(ouinon("Oui :", "on résout, sans chercher à impressionner.", NAVY));
  k.push(ouinon("Non :", "pas de superlatifs, pas de ton publicitaire, pas d'esbroufe.", RED));
  k.push(header("LE TON S'ADAPTE À L'INSTANT"));
  k.push(body("Même voix, registres différents selon ce que vit la personne."));
  k.push(lead("Quand elle réussit.", "On célèbre sobrement, puis on la remet en mouvement vers la suite. La victoire est la sienne, pas la nôtre."));
  k.push(lead("Quand elle échoue.", "Un examen raté, un dossier refusé : de l'empathie réelle, jamais de fausse gaieté. On reconnaît le coup, puis on montre le prochain pas."));
  k.push(lead("Quand elle est perdue.", "On rassure et on guide. Une action claire vaut mieux que dix explications."));
  k.push(lead("Quand quelque chose casse.", "Les messages d'erreur assument la faute de notre côté. On ne blâme jamais l'utilisateur, on ne le fait jamais se sentir bête."));
  k.push(header("TU OU VOUS"));
  k.push(body("Une décision, tenue partout. Dans les produits, nous disons tu, et du en allemand : Kebrane est un compagnon de route, pas une administration. La proximité est un choix, elle nous distingue du langage froid que nos utilisateurs subissent ailleurs."));
  k.push(body("Dans les registres institutionnels (mentions légales, presse, investisseurs), nous passons au vous, et Sie : par sérieux, jamais par distance."));
  k.push(header("LA VOIX EN SITUATION"));
  k.push(body("Les mêmes principes, en pratique. Voici comment Kebrane parle aux moments qui comptent."));
  k.push(subhead("Une erreur technique."));
  k.push(quote("« Quelque chose a bloqué de notre côté. Réessaie dans un instant, tes réponses sont sauvegardées. »"));
  k.push(subhead("Un paiement refusé."));
  k.push(quote("« Le paiement n'est pas passé et rien n'a été débité. Tu peux réessayer ou changer de moyen de paiement. »"));
  k.push(subhead("Un examen échoué."));
  k.push(quote("« Ce n'est pas le résultat espéré. Regardons ensemble ce qui a manqué, et préparons la prochaine tentative. »"));
  k.push(subhead("Un abonnement expiré."));
  k.push(quote("« Ton accès a pris fin. Tes données t'attendent : tu peux reprendre là où tu t'es arrêté quand tu veux. »"));
  k.push(subhead("Une réussite."));
  k.push(quote("« C'est réussi, et c'est ton travail. Voici la prochaine étape, quand tu es prêt. »"));
  k.push(subhead("Une demande qu'on ne peut pas satisfaire."));
  k.push(quote("« On ne peut pas faire cela pour l'instant, et on préfère te le dire clairement plutôt que te faire tourner en rond. Voici ce qui est possible à la place. »"));
  k.push(header("LES MOTS QUE NOUS CHOISISSONS"));
  k.push(subhead("Nous préférons"));
  k.push(bullet("des verbes d'action : ", "réussir, préparer, obtenir, avancer."));
  k.push(bullet("nommer la personne, pas son statut : ", "« toi qui prépares ton examen », pas « les candidats »."));
  k.push(bullet("les termes administratifs indispensables ", "(« examen », parfois « dossier »), mais toujours expliqués simplement."));
  k.push(bullet("dire concrètement ce qui va se passer, ", "étape par étape."));
  k.push(subhead("Nous bannissons"));
  k.push(bullet("le jargon technique ", "et les anglicismes gratuits."));
  k.push(bullet("le jargon administratif inutile, ", "quand un mot simple existe."));
  k.push(bullet("les promesses creuses : ", "« garanti », « en un clic », « sans effort »."));
  k.push(bullet("de réduire une personne ", "à « un dossier », « un requérant » ou « un usager »."));
  k.push(header("COMMENT NOUS NOMMONS"));
  k.push(body("Trois étages, une règle par étage. La maison mère est abstraite : Kebrane. Les divisions sont limpides : Kebrane Education, Kebrane Arrival. Les produits sont mémorables, en deux familles : « -Pass » pour franchir un examen (GermanPass, TCFPass, PermitPass), et des noms humains pour l'intégration (Arrival)."));
  k.push(body("Un nom nouveau se mérite : on ne baptise un produit que lorsqu'il peut vivre seul. Une fonctionnalité ne porte pas de marque."));
  signature().forEach(p => k.push(p));
  k.push(body("La signature vit en pied de page, sur les stores, à l'ouverture des applications. Jamais dans le nom du produit. Elle relie, elle ne domine pas."));
  k.push(golden("On reconnaît Kebrane à sa voix avant son logo. Si une phrase pourrait être signée par une administration, elle n'est pas de Kebrane."));
  await build("L-Identite-verbale-Kebrane.docx", "L'Identité verbale de Kebrane", k);
}

// ============ 3. PRINCIPES PRODUIT ============
async function principes() {
  const k = [];
  k.push(nameLine("K E B R A N E"));
  k.push(bigTitle("Les Principes", { before: 120, after: 0 }));
  k.push(bigTitle("Produit", { after: 60 }));
  k.push(subtitle("Les règles qui gouvernent chaque produit Kebrane, pour qu'ils donnent tous la même sensation."));
  k.push(meta("Document fondateur   ·   Version 0.9"));
  k.push(rule());
  k.push(header("POURQUOI CES PRINCIPES"));
  k.push(body("Le manifeste dit pourquoi Kebrane existe. Le livre de la culture dit comment nous nous comportons. Ces principes disent comment nous construisons. Ce sont les mêmes convictions, descendues jusque dans l'écran."));
  k.push(body("Un produit Kebrane se juge à une seule chose : la barrière qu'il fait disparaître."));
  k.push(body("Avant chaque décision produit, une question : quelle barrière fait-il tomber, pour qui, et comment saurons-nous qu'elle est tombée ? Si la réponse manque, le produit attend."));
  k.push(header("LA BARRIÈRE D'ABORD"));
  k.push(numbered("01", "Une barrière nommée, une personne nommée.", "Si tu ne peux pas dire quelle barrière tombe et pour qui, il n'y a pas encore de produit, seulement une envie."));
  k.push(numbered("02", "Nous bâtissons des passerelles, pas des destinations.", "Le meilleur produit est celui que l'utilisateur peut quitter librement une fois son objectif atteint, sans rien perdre de son autonomie. On conçoit pour la sortie réussie, pas pour la rétention."));
  k.push(numbered("03", "On mesure la barrière tombée, jamais le temps passé.", "Trois familles d'indicateurs, jamais l'engagement : les résultats (examen réussi, dossier accepté), les progrès que le produit permet vraiment (niveau gagné, erreurs réduites, délai de correction, parcours terminé), et les garde-fous (coût, plaintes, taux d'erreur, accessibilité). Le temps d'écran n'est pas un succès, c'est souvent un symptôme."));
  k.push(header("LA SENSATION KEBRANE"));
  k.push(numbered("04", "Compréhensible en une minute.", "Notre utilisateur arrive souvent stressé, dans une langue qui n'est pas la sienne. La clarté n'est pas un style, c'est un acte de respect."));
  k.push(numbered("05", "Multilingue par conception, déployé selon les besoins.", "L'architecture est multilingue dès l'origine, mais chaque langue s'active selon les besoins réels, avec une adaptation humaine et culturelle, jamais une traduction mécanique. La langue ne doit jamais devenir une barrière, dans le produit non plus."));
  k.push(numbered("06", "On montre le chemin, pas seulement la porte.", "À chaque étape, l'utilisateur sait où il en est, ce qui reste, et quoi faire ensuite. On dissout l'angoisse du parcours, on ne l'ajoute pas."));
  k.push(numbered("07", "Conçu pour un téléphone modeste et une connexion incertaine.", "Nos utilisateurs ne sont pas sur le dernier appareil en fibre. Concevoir pour la contrainte, c'est concevoir pour tout le monde."));
  k.push(header("NOS LIGNES ROUGES PRODUIT"));
  k.push(numbered("08", "Jamais de schémas sombres.", "Pas de faux compte à rebours, pas de culpabilisation, pas de désabonnement en labyrinthe. Nous refusons de gagner en piégeant."));
  k.push(numbered("09", "Nous ne monétisons pas la vulnérabilité.", "Le prix ne punit jamais la détresse. On ne fait pas payer plus cher celui qui est le plus coincé."));
  k.push(numbered("10", "L'utilisateur garde le contrôle de ses données.", "Il peut les consulter, les exporter et demander leur suppression. Nous n'en collectons que le minimum nécessaire. L'autonomie vaut aussi pour les données."));
  k.push(numbered("11", "L'IA conseille, elle ne prétend pas à l'infaillibilité.", "Nos évaluations indiquent leurs limites, s'appuient sur des critères vérifiables et permettent une révision humaine lorsque l'enjeu l'exige. Nous ne transformons jamais une estimation en certitude."));
  k.push(header("NOTRE DISCIPLINE DE CONSTRUCTION"));
  k.push(numbered("12", "Livrer petit, livrer vrai.", "Un vrai utilisateur avec un vrai problème vaut mieux que dix fonctionnalités imaginées."));
  k.push(numbered("13", "La cohérence entre produits est une promesse.", "Qui connaît GermanPass doit se sentir chez lui dans TCFPass en dix secondes. Mêmes repères, même ton, même logique. C'est ce qui fait une maison, pas une collection."));
  k.push(numbered("14", "La sécurité et l'accessibilité ne sont pas des fonctionnalités.", "Elles font partie du produit dès sa conception, pas des options ajoutées ensuite."));
  k.push(golden("Le meilleur produit Kebrane est celui que l'utilisateur peut quitter librement lorsqu'il a atteint son objectif. Nous construisons pour rendre service, pas pour retenir."));
  await build("Les-Principes-Produit-Kebrane.docx", "Les Principes Produit Kebrane", k);
}

(async () => { await culture(); await identite(); await principes(); console.log("ALL 3 WRITTEN"); })();
